// Generated by CoffeeScript 1.7.1
(function() {
  var Api, Util, debug, moment, util, _;

  util = require("util");

  moment = require("moment");

  _ = require("underscore");

  debug = require("debug")("Baseamp:Todo");

  Util = require("./Util");

  Api = (function() {
    function Api(input) {}

    Api.prototype.get = function() {};

    return Api;

  })();

  module.exports = Api;

}).call(this);
