// Generated by CoffeeScript 1.7.1
(function() {
  var Api, TodoList, TodoLists, Util, async, debug, fs, moment, request, util, _;

  util = require("util");

  request = require("request");

  moment = require("moment");

  _ = require("underscore");

  debug = require("debug")("Baseamp:Todo");

  Util = require("./Util");

  fs = require("fs");

  async = require("async");

  TodoLists = require("./TodoLists");

  TodoList = require("./TodoList");

  Api = (function() {
    Api.prototype.vcr = false;

    Api.prototype.endpoints = {
      get_people: "https://basecamp.com/{{{account_id}}}/api/v1/people.json",
      get_lists: "https://basecamp.com/{{{account_id}}}/api/v1/projects/{{{project_id}}}/todolists.json",
      post_lists: "https://basecamp.com/{{{account_id}}}/api/v1/projects/{{{project_id}}}/todolists.json",
      put_lists: "https://basecamp.com/{{{account_id}}}/api/v1/projects/{{{project_id}}}/todolists/{{{item_id}}}.json",
      post_todos: "https://basecamp.com/{{{account_id}}}/api/v1/prßojects/{{{project_id}}}/todolists/{{{item_id}}}/todos.json",
      put_todos: "https://basecamp.com/{{{account_id}}}/api/v1/projects/{{{project_id}}}/todos/{{{item_id}}}.json"
    };

    Api.prototype.uploadConcurrency = 1;

    Api.prototype.downloadConcurrency = 32;

    function Api(config) {
      this.config = config || {};
      if (this.config.username == null) {
        throw new Error("Need a username");
      }
      if (this.config.password == null) {
        throw new Error("Need a password");
      }
      if (this.config.account_id == null) {
        throw new Error("Need a account_id");
      }
      if (this.config.project_id == null) {
        throw new Error("Need a project_id");
      }
      if (this.config.fixture_dir == null) {
        this.config.fixture_dir = "" + __dirname + "/../test/fixtures";
      }
    }

    Api.prototype._itemIdMatch = function(type, displayField, item, remoteIds) {
      var remoteId, remoteItem, remoteItemsWithSameName, todo, _i, _len, _ref;
      if (!item.id || (remoteIds[type][item.id] == null)) {
        remoteItemsWithSameName = (function() {
          var _ref, _results;
          _ref = remoteIds[type];
          _results = [];
          for (remoteId in _ref) {
            remoteItem = _ref[remoteId];
            if (remoteItem[displayField] === item[displayField]) {
              _results.push(remoteItem);
            }
          }
          return _results;
        })();
        if (remoteItemsWithSameName.length) {
          item.id = remoteItemsWithSameName[remoteItemsWithSameName.length - 1].id;
        }
      }
      if (item.id && (remoteIds[type][item.id] == null)) {
        item.id = void 0;
      }
      if (type === "lists") {
        _ref = item.todos;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          todo = _ref[_i];
          todo.todolist_id = item.id;
        }
      }
      return item;
    };

    Api.prototype._uploadItems = function(type, displayField, items, remoteIds, cb) {
      var errors, q;
      errors = [];
      q = async.queue((function(_this) {
        return function(item, qCb) {
          var id, method, opts, payload, person, personIdsWithCallsign, remoteItem;
          item = _this._itemIdMatch(type, displayField, item, remoteIds);
          remoteItem = remoteIds[type][item.id];
          method = remoteItem != null ? "put" : "post";
          payload = item.apiPayload();
          if (payload.assignee != null) {
            personIdsWithCallsign = (function() {
              var _ref, _results;
              _ref = remoteIds.people;
              _results = [];
              for (id in _ref) {
                person = _ref[id];
                if (person.call_sign === payload.assignee) {
                  _results.push(person.id);
                }
              }
              return _results;
            })();
            if (personIdsWithCallsign.length > 1) {
              errors.push("These people have the same callsign! " + (personIdsWithCallsign.join(', ')) + ". Please fix that first. ");
              return qCb();
            } else if (personIdsWithCallsign.length === 1) {
              payload.assignee = {
                id: person.id,
                type: "Person"
              };
            }
          }
          if (method === "put" && !_this._itemDiffs(type, remoteItem, displayField, payload)) {
            debug("SKIP " + (_this._human(type, payload, displayField)));
            return qCb();
          }
          debug("PUSH " + (_this._human(type, payload, displayField)));
          opts = {
            method: method,
            url: _this.endpoints["" + method + "_" + type],
            replace: {
              item_id: item.id
            }
          };
          if (method === "post" && (type = "todos")) {
            opts.replace = {
              item_id: item.todolist_id
            };
          }
          return _this._request(opts, payload, function(err, data) {
            if (err) {
              errors.push("Errors while " + opts.method + " " + opts.url + ". " + err);
              return qCb();
            }
            item.id = data.id;
            return qCb();
          });
        };
      })(this), this.uploadConcurrency);
      q.drain = (function(_this) {
        return function() {
          if (errors.length) {
            return cb(errors.join('\n'));
          }
          return cb(null);
        };
      })(this);
      return q.push(items);
    };

    Api.prototype._human = function(type, item, displayField) {
      return ("" + type + " ") + item[displayField].substr(0, 20);
    };

    Api.prototype._itemDiffs = function(type, remoteItem, displayField, payload) {
      var diff, key, val;
      diff = [];
      for (key in payload) {
        val = payload[key];
        if (payload[key] !== remoteItem[key]) {
          debug("CHANGE '" + (this._human(type, payload, displayField)) + "'. Payload's key '" + key + "' is '" + val + "' while remoteItem's is '" + remoteItem[key] + "'");
          return true;
        }
      }
      return false;
    };

    Api.prototype.uploadTodoLists = function(localLists, cb) {
      var remoteIds;
      remoteIds = {
        lists: {},
        todos: {},
        people: {}
      };
      return async.waterfall([
        (function(_this) {
          return function(callback) {
            return _this.downloadPeople(function(err, people) {
              var person, _i, _len;
              if (err) {
                return callback(err);
              }
              for (_i = 0, _len = people.length; _i < _len; _i++) {
                person = people[_i];
                remoteIds.people[person.id] = person;
              }
              return callback(null);
            });
          };
        })(this), (function(_this) {
          return function(callback) {
            return _this.downloadTodoLists(function(err, remoteLists) {
              var list, remoteTodoLists, todo, _i, _j, _len, _len1, _ref, _ref1;
              if (err) {
                return callback(err);
              }
              remoteTodoLists = new TodoLists(remoteLists);
              _ref = remoteTodoLists.lists;
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                list = _ref[_i];
                remoteIds["lists"][list.id] = list;
                _ref1 = list.todos;
                for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
                  todo = _ref1[_j];
                  remoteIds["todos"][todo.id] = todo;
                }
              }
              return callback(null);
            });
          };
        })(this), (function(_this) {
          return function(callback) {
            return _this._uploadItems("lists", "name", localLists.lists, remoteIds, function(err) {
              return callback(err);
            });
          };
        })(this), (function(_this) {
          return function(callback) {
            var allTodos, list, todo, _i, _j, _len, _len1, _ref, _ref1;
            allTodos = [];
            _ref = localLists.lists;
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              list = _ref[_i];
              _ref1 = list.todos;
              for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
                todo = _ref1[_j];
                if (!todo) {
                  return callback(new Error("No todo!"));
                }
                if (todo.todolist_id == null) {
                  todo.todolist_id = list.id;
                }
                if (todo.todolist_id == null) {
                  debug(util.inspect({
                    todo: todo,
                    list_id: list.id
                  }));
                  return callback(new Error("Todo's todolist_id should be known here!"));
                }
                allTodos.push(todo);
              }
            }
            return _this._uploadItems("todos", "content", allTodos, remoteIds, function(err) {
              return callback(err);
            });
          };
        })(this)
      ], (function(_this) {
        return function(err, res) {
          return cb(err);
        };
      })(this));
    };

    Api.prototype.downloadPeople = function(cb) {
      debug("Retrieving people...");
      return this._request(this.endpoints["get_people"], null, (function(_this) {
        return function(err, people) {
          var i, person, _i, _len;
          if (err) {
            return cb(err);
          }
          for (i = _i = 0, _len = people.length; _i < _len; i = ++_i) {
            person = people[i];
            people[i].call_sign = Util.formatNameAsUnixHandle(person.name);
          }
          return cb(null, people);
        };
      })(this));
    };

    Api.prototype.downloadTodoLists = function(cb) {
      debug("Retrieving todolists...");
      return this._request(this.endpoints["get_lists"], null, (function(_this) {
        return function(err, lists) {
          var errors, list, q, retrieveUrls;
          if (err) {
            return cb(err);
          }
          retrieveUrls = (function() {
            var _i, _len, _results;
            _results = [];
            for (_i = 0, _len = lists.length; _i < _len; _i++) {
              list = lists[_i];
              if (list.url != null) {
                _results.push(list.url);
              }
            }
            return _results;
          })();
          if (!retrieveUrls.length) {
            debug("Found no lists urls (yet)");
            return cb(null, []);
          }
          errors = [];
          lists = [];
          q = async.queue(function(url, callback) {
            return _this._request(url, null, function(err, todoList) {
              if (err) {
                errors.push("Error retrieving " + url + ". " + err);
                return callback();
              }
              lists.push(todoList);
              return callback();
            });
          }, _this.downloadConcurrency);
          q.push(retrieveUrls);
          return q.drain = function() {
            if (errors.length) {
              return cb(errors.join('\n'));
            }
            return cb(null, lists);
          };
        };
      })(this));
    };

    Api.prototype._request = function(opts, payload, cb) {
      var data, filename, json;
      if (_.isString(opts)) {
        opts = {
          url: opts
        };
      }
      opts.url = Util.template(opts.url, this.config, opts.replace);
      opts.body = payload;
      if (opts.method == null) {
        opts.method = "get";
      }
      if (opts.json == null) {
        opts.json = true;
      }
      if (opts.auth == null) {
        opts.auth = {
          username: this.config.username,
          password: this.config.password
        };
      }
      if (opts.headers == null) {
        opts.headers = {
          "User-Agent": "Baseamp (https://github.com/kvz/baseamp)"
        };
      }
      if (opts.url.substr(0, 7) === "file://") {
        filename = opts.url.replace(/^file\:\/\//, "");
        json = fs.readFileSync(Util.template(filename, this.config));
        data = JSON.parse(json);
        return cb(null, data);
      }
      return request[opts.method](opts, (function(_this) {
        return function(err, req, data) {
          var msg, status;
          status = "" + req.statusCode;
          if (!status.match(/[23][0-9]{2}/)) {
            msg = "Status code " + status + " during " + (opts.method.toUpperCase()) + " '" + opts.url + "'";
            err = new Error(msg);
            return cb(err, data);
          }
          if (_this.vcr === true && opts.url.substr(0, 7) !== "file://") {
            debug("VCR: Recording " + opts.url + " to disk so we can watch later : )");
            fs.writeFileSync(Util.template(_this._toFixtureFile(opts.url), _this.config), JSON.stringify(_this._toFixture(data), null, 2));
          }
          return cb(err, data);
        };
      })(this));
    };

    Api.prototype._toFixtureVal = function(val, key) {
      var newVal;
      newVal = _.clone(val);
      if (_.isObject(newVal) || _.isArray(newVal)) {
        newVal = this._toFixture(newVal);
      } else if (key === "account_id") {
        newVal = 11;
      } else if (key === "url") {
        newVal = "file://" + this._toFixtureFile(newVal);
      } else if (("" + key).slice(-4) === "_url") {
        newVal = "http://example.com/";
      } else if (_.isNumber(newVal)) {
        newVal = 22;
      } else if (_.isBoolean(newVal)) {
        newVal = false;
      }
      return newVal;
    };

    Api.prototype._toFixture = function(obj) {
      var key, newObj, val, _i, _len;
      newObj = _.clone(obj);
      if (_.isObject(newObj)) {
        for (key in newObj) {
          val = newObj[key];
          newObj[key] = this._toFixtureVal(val, key);
        }
      } else if (_.isArray(newObj)) {
        for (key = _i = 0, _len = newObj.length; _i < _len; key = ++_i) {
          val = newObj[key];
          newObj[key] = this._toFixtureVal(val, key);
        }
      } else {
        newObj = this._toFixtureVal(newObj);
      }
      return newObj;
    };

    Api.prototype._toFixtureFile = function(url) {
      var filename, parts;
      parts = url.split("/projects/");
      url = parts.pop();
      filename = "{{{fixture_dir}}}" + "/";
      filename += url.replace(/[^a-z0-9]/g, ".");
      return filename;
    };

    return Api;

  })();

  module.exports = Api;

}).call(this);

//# sourceMappingURL=Api.map
