// Generated by CoffeeScript 1.7.1
(function() {
  var Baseamp, debug, request;

  request = require("request");

  debug = require("debug")("Baseamp:Baseamp");

  Baseamp = (function() {
    function Baseamp(_arg) {
      var _ref;
      _ref = _arg != null ? _arg : {}, this.username = _ref.username, this.password = _ref.password, this.projectId = _ref.projectId;
      if (!this.username) {
        throw new Error("Need a username");
      }
    }

    Baseamp.prototype["import"] = function(file, cb) {
      console.log(file);
      return cb(null);
    };

    module.exports = Baseamp;

    return Baseamp;

  })();

}).call(this);
