// Generated by CoffeeScript 1.7.1
(function() {
  var Base;

  Base = (function() {
    function Base() {}

    Base.prototype._extractId = function(line) {
      var id, m;
      id = void 0;
      m = ("" + line).match(/\s+\(#(\d+)\)$/);
      if (m != null ? m[1] : void 0) {
        id = m[1];
        line = line.replace(m[0], "");
      }
      return {
        id: id,
        line: line
      };
    };

    return Base;

  })();

}).call(this);
