// Generated by CoffeeScript 1.7.1
(function() {
  var Api, Baseamp, TodoLists, Util, debug, fs, packageJson, util, _;

  util = require("util");

  fs = require("fs");

  _ = require("underscore");

  debug = require("debug")("Baseamp:Baseamp");

  TodoLists = require("./TodoLists");

  Util = require("./Util");

  Api = require("./Api");

  packageJson = require("../package.json");

  Baseamp = (function() {
    function Baseamp(config) {
      this.api = new Api(config);
    }

    Baseamp.prototype.version = function(file, cb) {
      var stderr, stdout;
      stdout = "";
      stderr = "";
      stderr += "v" + packageJson.version;
      return cb(null, stdout, stderr);
    };

    Baseamp.prototype.help = function(file, cb) {
      var stderr, stdout;
      stdout = "";
      stderr = "";
      stderr += "" + packageJson.name + " v" + packageJson.version + "\n";
      stderr += " \n";
      stderr += " Usage:\n";
      stderr += " \n";
      stderr += "   " + packageJson.name + " action [args]\n";
      stderr += " \n";
      stderr += " Actions:\n";
      stderr += " \n";
      stderr += "   download [file]  Downloads latest todos from Basecamp, saved to file or STDOUT(-)\n";
      stderr += "     upload [file]  Uploads latest todos to Basecamp, sourcing from file or STDIN(-)\n";
      stderr += "    version         Reports version\n";
      stderr += "       help         This page\n";
      return cb(null, stdout, stderr);
    };

    Baseamp.prototype.download = function(file, cb) {
      return this.api.downloadTodoLists(function(err, todoLists) {
        var buf, stderr, stdout;
        if (err) {
          return cb(err);
        }
        todoLists = new TodoLists(todoLists);
        buf = todoLists.toMarkdown();
        if (file === "-") {
          stderr = "";
          stdout = buf;
        } else {
          stderr = "Writing todo to " + file + "\n";
          stdout = "";
          fs.writeFileSync(file, stdout, "utf-8");
        }
        return cb(null, stdout, stderr);
      });
    };

    Baseamp.prototype.upload = function(file, cb) {
      var buf, stderr, stdout, todoLists;
      stderr = "Reading todo from " + file + "\n";
      stdout = "";
      buf = fs.readFileSync(file, "utf-8");
      todoLists = new TodoLists(buf);
      return this.api.uploadTodoLists(todoLists, function(err) {
        if (err) {
          return cb(err);
        }
        return cb(null, stdout, stderr);
      });
    };

    return Baseamp;

  })();

  module.exports = Baseamp;

}).call(this);

//# sourceMappingURL=Baseamp.map
