// Generated by CoffeeScript 1.7.1
(function() {
  var TodoList, TodoLists, Util, debug, moment, util, _;

  util = require("util");

  moment = require("moment");

  _ = require("underscore");

  debug = require("debug")("Baseamp:TodoLists");

  TodoList = require("./TodoList");

  Util = require("./Util");

  TodoLists = (function() {
    function TodoLists(input, defaults) {
      var todoLists;
      if (input == null) {
        todoLists = {};
      } else if (_.isString(input)) {
        todoLists = this.fromMarkdown(input);
      } else {
        todoLists = this.fromApi(input);
      }
      _.defaults(todoLists, defaults);
      this.lists = todoLists.lists;
    }

    TodoLists.prototype.fromApi = function(input) {
      var list, todoLists, _i, _len;
      todoLists = {
        lists: []
      };
      for (_i = 0, _len = input.length; _i < _len; _i++) {
        list = input[_i];
        todoLists.lists.push(new TodoList(list));
      }
      return todoLists;
    };

    TodoLists.prototype.fromMarkdown = function(str) {
      var cntPosition, part, parts, todoLists, _i, _len;
      todoLists = {
        lists: []
      };
      parts = str.split(/^##\s+/m);
      cntPosition = 0;
      for (_i = 0, _len = parts.length; _i < _len; _i++) {
        part = parts[_i];
        if (!part.trim()) {
          continue;
        }
        part = "## " + part;
        cntPosition++;
        todoLists.lists.push(new TodoList(part, {
          position: cntPosition
        }));
      }
      return todoLists;
    };

    TodoLists.prototype.toMarkdown = function() {
      var buf, todoList, _i, _len, _ref;
      buf = "";
      _ref = this.lists;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        todoList = _ref[_i];
        buf += todoList.toMarkdown();
      }
      return buf;
    };

    return TodoLists;

  })();

  module.exports = TodoLists;

}).call(this);

//# sourceMappingURL=TodoLists.map
