// Generated by CoffeeScript 1.7.1
(function() {
  var Todo, TodoList, debug, moment, util, _;

  util = require("util");

  moment = require("moment");

  _ = require("underscore");

  debug = require("debug")("Baseamp:TodoList");

  Todo = require("./Todo");

  TodoList = (function() {
    TodoList.prototype.name = "";

    TodoList.prototype.todos = [];

    function TodoList(todoList) {
      var category, todo, todos, _i, _len, _ref;
      if (_.isString(todoList)) {
        todoList = this.fromMarkdown(todoList);
      }
      this.name = todoList.name;
      _ref = todoList.todos;
      for (category in _ref) {
        todos = _ref[category];
        for (_i = 0, _len = todos.length; _i < _len; _i++) {
          todo = todos[_i];
          if (!todo.category) {
            todo.category = category;
          }
          this.todos.push(new Todo(todo));
        }
      }
    }

    TodoList.prototype.fromMarkdown = function(str) {
      var line, lines, todoList, _i, _len;
      todoList = {
        todos: {
          all: []
        }
      };
      str = ("" + str).replace("\r", "");
      lines = str.split("\n");
      for (_i = 0, _len = lines.length; _i < _len; _i++) {
        line = lines[_i];
        if (line.substr(0, 2) === "##") {
          todoList.name = line.replace(/^##\s+/, "");
          continue;
        }
        if (!line.trim()) {
          continue;
        }
        todoList.todos.all.push(new Todo(line));
      }
      return todoList;
    };

    TodoList.prototype.toMarkdown = function() {
      var buf, todo, _i, _len, _ref;
      buf = "## " + this.name + "\n";
      buf += "\n";
      _ref = this.todos;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        todo = _ref[_i];
        buf += todo.toMarkdown();
      }
      buf += "\n\n";
      return buf;
    };

    return TodoList;

  })();

  module.exports = TodoList;

}).call(this);
