// Generated by CoffeeScript 1.7.1
(function() {
  var TodoList, TodoLists, Util, debug, moment, util, _;

  util = require("util");

  moment = require("moment");

  _ = require("underscore");

  debug = require("debug")("Baseamp:TodoLists");

  TodoList = require("./TodoList");

  Util = require("./Util");

  TodoLists = (function() {
    function TodoLists(todoLists) {
      var l, _i, _len;
      if (_.isString(todoLists)) {
        todoLists = this.fromMarkdown(todoLists);
        this.lists = (todoLists != null ? todoLists.lists : void 0) || [];
      } else {
        this.lists = [];
        for (_i = 0, _len = todoLists.length; _i < _len; _i++) {
          l = todoLists[_i];
          this.lists.push(new TodoList(l));
        }
      }
    }

    TodoLists.prototype.fromMarkdown = function(str) {
      var part, parts, todoLists, _i, _len;
      parts = str.split(/^##\s+/m);
      todoLists = {
        lists: []
      };
      for (_i = 0, _len = parts.length; _i < _len; _i++) {
        part = parts[_i];
        if (!part.trim()) {
          continue;
        }
        part = "## " + part;
        todoLists.lists.push(new TodoList(part));
      }
      return todoLists;
    };

    TodoLists.prototype.toMarkdown = function() {
      var buf, todoList, _i, _len, _ref;
      buf = "";
      _ref = this.lists;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        todoList = _ref[_i];
        buf += todoList.toMarkdown();
      }
      return buf;
    };

    return TodoLists;

  })();

  module.exports = TodoLists;

}).call(this);
