// Generated by CoffeeScript 1.7.1
(function() {
  var TodoList, TodoLists, Util, debug, moment, util, _;

  util = require("util");

  moment = require("moment");

  _ = require("underscore");

  debug = require("debug")("Baseamp:TodoLists");

  TodoList = require("./TodoList");

  Util = require("./Util");

  TodoLists = (function() {
    function TodoLists(input, defaults) {
      var todoLists;
      if (input == null) {
        todoLists = {};
      } else if (_.isString(input)) {
        todoLists = this.fromMarkdown(input);
      } else {
        todoLists = this.fromApi(input);
      }
      _.defaults(todoLists, defaults);
      this.lists = todoLists.lists;
    }

    TodoLists.prototype.searchBetween = function(start, end) {
      var due_at, list, todo, todosInRange, _i, _j, _len, _len1, _ref, _ref1;
      start = +moment(start);
      end = +moment(end);
      todosInRange = [];
      _ref = this.lists;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        list = _ref[_i];
        _ref1 = list.todos;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          todo = _ref1[_j];
          if (todo.due_at != null) {
            due_at = +moment(todo.due_at);
            if (due_at >= start && due_at <= end) {
              todosInRange.push(todo);
            }
          }
        }
      }
      Util.sortByObjField(todosInRange, "due_at", "completed");
      return todosInRange;
    };

    TodoLists.prototype.fromApi = function(input) {
      var list, todoLists, _i, _len;
      todoLists = {
        lists: []
      };
      for (_i = 0, _len = input.length; _i < _len; _i++) {
        list = input[_i];
        todoLists.lists.push(new TodoList(list));
      }
      Util.sortByObjField(todoLists.lists, "position");
      return todoLists;
    };

    TodoLists.prototype.fromMarkdown = function(str) {
      var line, list, part, parts, todoLists, _i, _len;
      todoLists = {
        lists: []
      };
      parts = str.split(/^##\s+/m);
      for (_i = 0, _len = parts.length; _i < _len; _i++) {
        part = parts[_i];
        if (!part.trim()) {
          continue;
        }
        line = "## " + part;
        list = new TodoList(line, {
          position: todoLists.lists.length + 1
        });
        if (list != null) {
          todoLists.lists.push(list);
        }
      }
      return todoLists;
    };

    TodoLists.prototype.toMarkdown = function() {
      var buf, todoList, _i, _len, _ref;
      buf = "";
      Util.sortByObjField(this.lists, "position");
      _ref = this.lists;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        todoList = _ref[_i];
        buf += todoList.toMarkdown();
      }
      return buf;
    };

    return TodoLists;

  })();

  module.exports = TodoLists;

}).call(this);

//# sourceMappingURL=TodoLists.map
