// Generated by CoffeeScript 1.7.1
(function() {
  var Mustache, Util,
    __slice = [].slice;

  Mustache = require("mustache");

  Util = (function() {
    function Util() {}

    Util.extractId = function(line) {
      var id, m;
      id = void 0;
      m = ("" + line).match(/\s+\(#(\d+)\)$/);
      if (m != null ? m[1] : void 0) {
        id = m[1];
        line = line.replace(m[0], "");
      }
      return {
        id: id,
        line: line
      };
    };

    Util.sortByObjField = function(array, field) {
      return array.sort(function(a, b) {
        if (a[field] < b[field]) {
          return -1;
        }
        if (a[field] > b[field]) {
          return 1;
        }
        return 0;
      });
    };

    Util.template = function() {
      var args, key, params, replace, url, val, _i, _len;
      url = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      replace = {};
      for (_i = 0, _len = args.length; _i < _len; _i++) {
        params = args[_i];
        for (key in params) {
          val = params[key];
          replace[key] = val;
        }
      }
      return Mustache.render(url, replace);
    };

    return Util;

  })();

  module.exports = Util;

}).call(this);

//# sourceMappingURL=Util.map
